import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split, Dataset
from parameters import batch_size
import json
import os
import numpy as np
from collections import defaultdict
from typing import Any, DefaultDict, Dict, List, Tuple
from sklearn.model_selection import train_test_split
from preparation import *

# Define transformations for the training and testing sets
transform = transforms.Compose(
    [
        transforms.ToTensor(),
        transforms.Normalize((0.5,), (0.5,)),  # Normalize the data to [-1, 1]
    ]
)


def split_dataset(dataset, ratio=0.9):
    train_size = int(ratio * len(dataset))
    val_size = len(dataset) - train_size
    train_subset, val_subset = random_split(dataset, [train_size, val_size])
    return train_subset, val_subset


class FemnistClientDataset(Dataset):
    def __init__(self, inputs: list[list[float]], labels: list[int], transform=None):
        if len(inputs) != len(labels):
            raise Exception(
                f"Different number of inputs ({len(inputs)}) and labels ({len(labels)})"
            )
        self.x, self.y = inputs, labels
        self.transform = transform

    def __getitem__(self, index):
        target_data = self.y[index]
        input_data = np.array(self.x[index]).reshape(28, 28)
        if self.transform:
            input_data = self.transform(input_data)

        return input_data.to(torch.float32), target_data

    def __len__(self):
        return len(self.y)


# standard MNIST
# mnist_train_dataset = datasets.MNIST(
#     root="./data", train=True, download=True, transform=transform
# )
# mnist_test_dataset = datasets.MNIST(
#     root="./data", train=False, download=True, transform=transform
# )
# mnist_train_subset, mnist_val_subset = split_dataset(mnist_train_dataset)


# mnist_train_loader = DataLoader(mnist_train_subset, batch_size=batch_size, shuffle=True)
# mnist_val_loader = DataLoader(mnist_val_subset, batch_size=batch_size, shuffle=True)
# mnist_test_loader = DataLoader(mnist_test_dataset, batch_size=batch_size, shuffle=False)


# Extended MNIST
# emnist_train_dataset = datasets.EMNIST(
#     root="./data", split="balanced", train=True, download=True, transform=transform
# )
# emnist_test_dataset = datasets.EMNIST(
#     root="./data", split="balanced", train=False, download=True, transform=transform
# )
# emnist_train_subset, emnist_val_subset = split_dataset(emnist_train_dataset)

# emnist_train_loader = DataLoader(
#     emnist_train_subset, batch_size=batch_size, shuffle=True
# )
# emnist_val_loader = DataLoader(emnist_val_subset, batch_size=batch_size, shuffle=True)
# emnist_test_loader = DataLoader(
#     emnist_test_dataset, batch_size=batch_size, shuffle=False
# )


# TODO: this is assuming that data_path points to tha all_data directory and not the train/test ones
# the proper directories and files should be accessed
def structure_dataset(data_path: str, users_number: int):
    """Function to structure the FEMNIST dataset by user so it can be used for a
    federated learning simulation.

    Parameters
    ----------
    data_path: str
        Path to the directory containing the .json files generated by the LEAF preprocess.sh script.
        For more info see: https://github.com/TalwalkarLab/leaf/blob/master/data/femnist/README.md
    users_number: int
        The number of users to extract
    """
    included = 0
    dataloaders_by_user = []
    files = [f for f in os.listdir(data_path) if f.endswith(".json")]
    files.sort()

    for file_name in files:
        with open(os.path.join(data_path, file_name), "r") as file:
            print(f"Parsing file {file_name}")
            # this json object has 3 keys:
            # `users` list of user ids,
            # `num_samples` list of images per user,
            # `user_data` (flattened) image data and label, partitioned per user
            dataset = json.load(file)
            user_data = dataset["user_data"]
            for user_id in user_data:
                x_list, y_list = user_data[user_id]["x"], user_data[user_id]["y"]
                print(
                    f"\tIncluding user: {user_id} having {len(x_list)} images with id: {included}"
                )
                user_loader = DataLoader(
                    FemnistClientDataset(x_list, y_list, transform),
                    batch_size=batch_size,
                    shuffle=True,
                )
                dataloaders_by_user.append(user_loader)

                included += 1
                if included >= users_number:
                    return dataloaders_by_user

    return dataloaders_by_user


structure_dataset("C:\\Users\\danie\\Desktop\\json", 100)
