import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split, Dataset
from parameters import batch_size
import json
import os
import numpy as np
from collections import defaultdict
from typing import Any, DefaultDict, Dict, List, Tuple
from sklearn.model_selection import train_test_split
from preparation import *

# Define transformations for the training and testing sets
transform = transforms.Compose(
    [
        transforms.ToTensor(),
        transforms.Normalize((0.5,), (0.5,)),  # Normalize the data to [-1, 1]
    ]
)


def split_dataset(dataset, ratio=0.9):
    train_size = int(ratio * len(dataset))
    val_size = len(dataset) - train_size
    train_subset, val_subset = random_split(dataset, [train_size, val_size])
    return train_subset, val_subset


# standard MNIST
# mnist_train_dataset = datasets.MNIST(
#     root="./data", train=True, download=True, transform=transform
# )
# mnist_test_dataset = datasets.MNIST(
#     root="./data", train=False, download=True, transform=transform
# )
# mnist_train_subset, mnist_val_subset = split_dataset(mnist_train_dataset)


# mnist_train_loader = DataLoader(mnist_train_subset, batch_size=batch_size, shuffle=True)
# mnist_val_loader = DataLoader(mnist_val_subset, batch_size=batch_size, shuffle=True)
# mnist_test_loader = DataLoader(mnist_test_dataset, batch_size=batch_size, shuffle=False)


# Extended MNIST
# emnist_train_dataset = datasets.EMNIST(
#     root="./data", split="balanced", train=True, download=True, transform=transform
# )
# emnist_test_dataset = datasets.EMNIST(
#     root="./data", split="balanced", train=False, download=True, transform=transform
# )
# emnist_train_subset, emnist_val_subset = split_dataset(emnist_train_dataset)

# emnist_train_loader = DataLoader(
#     emnist_train_subset, batch_size=batch_size, shuffle=True
# )
# emnist_val_loader = DataLoader(emnist_val_subset, batch_size=batch_size, shuffle=True)
# emnist_test_loader = DataLoader(
#     emnist_test_dataset, batch_size=batch_size, shuffle=False
# )


def structure_dataset(
    data_path: str, users_number: int
) -> list[list[tuple[list[float], int]]]:
    """Function to structure the FEMNIST dataset by user so it can be used for a
    federated learning simulation.

    Parameters
    ----------
    data_path: str
        Path to the directory containing the .json files generated by the LEAF preprocess.sh script
        for more info see: https://github.com/TalwalkarLab/leaf/blob/master/data/femnist/README.md
    users_number: int
        The number of users to extract

    Returns
    -------
    list[list[tuple[list[float], int]]]
        List of length users_number containing, for each entry, the list of data for that user, that is a list of tuples
        where the first element is a 784 list for the input and the second is an int representing the class of the image
    """
    included = 0
    data_by_user = []
    files = [f for f in os.listdir(data_path) if f.endswith(".json")]
    files.sort()

    for file_name in files:
        with open(os.path.join(data_path, file_name), "r") as file:
            # this json object has 3 keys:
            # `users` list of user ids,
            # `num_samples` list of images per user,
            # `user_data` (flattened) image data and label, partitioned per user
            dataset = json.load(file)
            user_data = dataset["user_data"]
            for user_id in user_data:
                x_list, y_list = user_data[user_id]["x"], user_data[user_id]["y"]
                print(
                    f"Including user: {user_id} having {len(x_list)} images with id: {included}"
                )
                for i in range(len(x_list)):
                    data_by_user.append((x_list[i], y_list[i]))

                included += 1
                if included >= users_number:
                    return data_by_user

    return data_by_user
