defaults:
  - _self_

sim_cfg:
  num_rounds: 5
  num_cpus: 2
  num_gpus: 0.0

train_cfg:
  epochs: 6
  lr: 0.01
  momentum: 0.9

data_cfg:
  only_digits: false
  num_writers: 100
  hybrid_ratio: 0.2
  batch_size: 32
  val_ratio: 0.1
  # TODO: to be supported
  test_ratio: 0.1

hydra:
  run:
    dir: .
