defaults:
  - _self_

partitioning: horizontal

sim_cfg:
  num_rounds: 20
  num_cpus: 2
  num_gpus: 0.0

train_cfg:
  epochs: 3
  optimizer:
    _target_: torch.optim.SGD
    lr: 0.01
    momentum: 0.9
  loss_fn:
    _target_: torch.nn.CrossEntropyLoss

data_cfg:
  num_clients: 200
  hybrid_ratio: 0.1
  batch_size: 32
  val_ratio: 0.0
  test_ratio: 0.1
  dataset: femnist
  # warning: these values must always be changed together
  only_digits: false
  num_classes: 62

hydra:
  # mode: MULTIRUN
  sweeper:
    params:
      train_cfg.optimizer.lr: 0.01, 0.06
      data_cfg.hybrid_ratio: 0.0, 0.05, 0.1, 0.2, 0.3
      data_cfg.num_clients: 750, 100
  run:
    dir: .
