defaults:
  - _self_

partitioning: horizontal

sim_cfg:
  num_rounds: 20
  num_cpus: 2
  num_gpus: 0.0

train_cfg:
  epochs: 8
  optimizer:
    _target_: torch.optim.SGD
    lr: 0.01
    momentum: 0.9
  loss_fn:
    _target_: torch.nn.CrossEntropyLoss

data_cfg:
  num_clients: 9
  hybrid_ratio: 0.0
  hybrid_method: unify
  bias_factor: 0.4
  batch_size: 32
  dataset: har
  num_classes: 6

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      data_cfg.num_clients: 9, 20, 50
      data_cfg.hybrid_ratio: 0.0, 0.05, 0.1
      data_cfg.hybrid_method: unify, share, share-disjoint
  run:
    dir: .
