defaults:
  - _self_

partitioning: vertical

sim_cfg:
  num_rounds: 20
  num_cpus: 2
  num_gpus: 0.0

train_cfg:
  epochs: 64
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.01
    # momentum: 0.9
  loss_fn:
    _target_: torch.nn.CrossEntropyLoss

data_cfg:
  num_clients: 3
  hybrid_ratio: 0.0
  batch_size: 32
  dataset: har
  num_classes: 6

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      train_cfg.optimizer.lr: 0.001, 0.01, 0.1
      train_cfg.optimizer._target_: torch.optim.SGD, torch.optim.Adam
      train_cfg.epochs: 8, 64
      data_cfg.num_clients: 3, 11
  run:
    dir: .
